### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by mimvahedi** [benbusby/farside#145]
with adding some css like this
```css
@media (prefers-color-scheme: dark) {
  html {
    color: #fff;
    background: #112;
  }
  a:link {
    color: inherit;
  }
  a:visited {
    color: #888;
  }
}
```
